POST  http://localhost:3003/signup
Content-Type: application/json


{

"name": "Cleto Sanchez", 
"email": "cleto@gmail.com", 
"password": "1234567"


}
###
GET http://localhost:3003/ping
###
POST http://localhost:3003/login 
Content-Type: application/json

{

"name": "Mauricio Toledo", 
"email": "maurilium@gmail.com", 
"password": "1234567"


}
###
GET http://localhost:3003/all
Content-Type:  application/json

{

}
###
POST http://localhost:3003/recipe 
Content-Type: application/json

{
    "title": "ovo mexido ", 
    "description": "coloque o ovo na panela e mexa."
}
